server:
  port: 9090
spring:
  messages:
    basename: i18n/message
    encoding: UTF-8
management:
  security:
    enabled: false
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:54320/demodb
    username: postgres
    password: password
    pool-size: 30